CREATE TABLE LOCATION(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(50),
CREATEDATE TIMESTAMP,
CREATEDUSER VARCHAR(20),
LASTMODIFIED TIMESTAMP,
UPDATEDUSER VARCHAR(20)
);
